version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo start prebuild and end it here
  build:
    commands:
      - echo Running unit tests with pytest...
      - pytest --junitxml=report.xml=reports/reports.xml --tb=short  #Generate a JUnit report and show only the first line of the traceback
  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - "**/*"
  base-directory: . # the base directory of the artifacts

reports:
  pytest_reports:
    files:
      - "reports/reports.xml"
    discard-paths: yes